apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lk733jo3z-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lk733jo3z-dotnet-basic-gitops